name: build-petr4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout/main
        uses: actions/checkout@v3
      
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.0'
          dune-cache: false
          opam-repositories: |
            coq-released: https://coq.inria.fr/opam/released
          opam-pin: true
          opam-local-packages: "*.opam"

            #      - name: build-ubuntu
            #run: ./.github/scripts/build-petr4-ubuntu.sh
            #shell: bash

      - name: ci-test
        run: make ci-test

      - name: test-gcl-compiler
        run: ./.github/scripts/test-gcl-compiler.sh
        shell: bash
